### ISSUE TITLE
error de codigo en drawbot - bloque levantar

### ISSUE THREAD

**Issue by yn1v** [valentinbasel/icaro#7]
Valentin
encontre un bug muy pavo .... en drobot.levantar ... pusiste drowbot.levantar
:disappointed::disappointed:

**Comment by yn1v** [comment]
![photo5127515795906209820](https://user-images.githubusercontent.com/672344/43677936-9abc2ff8-97c7-11e8-8fb4-dc10e353be7f.jpg)

**Comment by yn1v** [comment]
Valentin
Levantar drawbot no debería tener argumentos...

**Comment by valentinbasel** [comment]
resuelto :-D
