### ISSUE TITLE
automatizar configuracion de usuarios

### ISSUE THREAD

**Issue by yn1v** [valentinbasel/icaro#9]
el usuario necesita ser parte de los grupos dialout y microchip
(Ver issue #8 se supone que se creara el grupo. Es relacionado pero esto es otro concepto) 
Seria deseable que se automatizara esto.

1.- Las instrucciones actuales usan sudo. Eso supone que sudo esta configurado, lo cual no se debería asumir porque no es parte de la configuración estandar de fedora
2.- No se deben agregar los usuarios de forma automatica, puesto que agrega todos los usuarios. No es "legal" segun lineamientos de empaquetamiento. Tampoco es una buena idea.
3.- Seria bueno si se pueden agregar desde el software sin requerir permisos de administrador. No deberia ser problema para el grupo microchip. Es posible que tener acceso a puertos de comunicación (dialout) se vea como un riesgo de seguridad.
4.- tomar en cuenta que a la hora de agregar usuarios a grupos la mayor parte del tiempo hay que cerrar sesión de usuario y volver a abrir la sesion para que los permisos se carguen/apliquen
5.- creo que es buena idea que aunque esto se automatice, el programa por lo menos la primera vez confirme grupos y usuarios

**Comment by valentinbasel** [comment]
la otra posibilidad es usar udev y darles permisos 0666 a los puerto ATM

y no haria falta estar en el grupo dialout.

KERNEL=="ttyACM[0-9]*",MODE="0666"
(aca si lo que queremos es que solo los dispositivos pinguino sean tengan esos permisos):

ACTION=="add", KERNEL=="ttyACM[0-9]*", ATTRS{idVendor}==" aca_el_id", ATTRS{idProduct}=="aca_el_id_producto", MODE="0666"
